version: "3.9"
services:
  mosquitto:
    image: eclipse-mosquitto:latest
    container_name: mosquitto-broker
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf:ro
    ports:
      - "1883:1883" # MQTT
      - "9001:9001" # WebSockets (if enabled in your config)
    restart: unless-stopped

